GENERAL:
  experiment: all
  seed: 0

DATA:
  # data path
  root_dir: F:/dataset/Teeth3DS/data
  split_dir: F:/dataset/Teeth3DS/split
  # batch_size per gpu
  batch_size: 2
  # sample
  num_points: 10000
  # augmentation
  augmentation: True
  # upper/lower

STRUCTURE:
  k: 20
  input_channels: 15
  output_channels: 17
  query_num: 80
  n_edgeconvs_backbone: 5
  emb_dims: 1024
  global_pool_backbone: avg   # max or avg
  norm: instance
  use_stn: True # False # spatial transformer network
  dynamic: False
  dropout: 0.

TRAIN:
  max_epochs: 200
  weight_decay: 0.0001
  delta: 0.1667
  load_from_checkpoint:
  resume_from_checkpoint:

  # one cycle lr scheduler
  lr_max: 0.001
  pct_start: 0.1    # percentage of the cycle spent increasing lr
  div_factor: 25    # determine the initial lr (lr_max / div_factor)
  final_div_factor: 1e4   # determine the final lr (lr_max / final_div_factor)
  start_epoch: 0

  train_file: training_all.txt
  train_workers: 1

  val_workers: 1
  val_file: testing_all.txt

  test_workers: 1
  test_file: testing_all.txt